"""lat_y_longitud

Revision ID: 241e3dadaa31
Revises: aea868388561
Create Date: 2021-07-21 19:51:19.853505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241e3dadaa31'
down_revision = 'aea868388561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('projects', sa.Column('lon', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'lon')
    op.drop_column('projects', 'lat')
    # ### end Alembic commands ###
