"""path field

Revision ID: 2c6abac12b2b
Revises: 6578cbc0f974
Create Date: 2021-07-13 18:32:37.831799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6abac12b2b'
down_revision = '6578cbc0f974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'path')
    # ### end Alembic commands ###
