"""video_url_project_field

Revision ID: 6578cbc0f974
Revises: 142e9ab35c0b
Create Date: 2021-07-09 21:47:18.815955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6578cbc0f974'
down_revision = '142e9ab35c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('video', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'video')
    # ### end Alembic commands ###
