"""path field

Revision ID: 6eb92849a524
Revises: 6578cbc0f974
Create Date: 2021-07-13 18:01:05.236571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb92849a524'
down_revision = '6578cbc0f974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('path', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'path')
    # ### end Alembic commands ###
