"""path field null allow

Revision ID: 9a966bad99b0
Revises: 6eb92849a524
Create Date: 2021-07-13 18:26:41.801682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a966bad99b0'
down_revision = '6eb92849a524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'path',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'path',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
