"""creation date field

Revision ID: a70ba64d7af7
Revises: 2a067442affb
Create Date: 2021-07-18 21:49:11.322579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70ba64d7af7'
down_revision = '2a067442affb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column(
        'creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'creation_date')
    # ### end Alembic commands ###
