"""create createdOn

Revision ID: aea868388561
Revises: a70ba64d7af7
Create Date: 2021-07-19 17:31:55.718736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aea868388561'
down_revision = 'a70ba64d7af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('createdOn', sa.String(length=128), nullable=True))
    op.drop_column('projects', 'creation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'createdOn')
    # ### end Alembic commands ###
