"""add rating

Revision ID: c967c71ad744
Revises: 241e3dadaa31
Create Date: 2021-07-24 00:09:20.338305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c967c71ad744'
down_revision = '241e3dadaa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_projects2',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id', 'project_id')
                    )
    op.add_column('projects', sa.Column(
        'totalRatings', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'rating')
    op.drop_column('projects', 'totalRatings')
    op.drop_table('user_favorite_projects2')
    # ### end Alembic commands ###
