"""create rating table

Revision ID: dd50d9a94e77
Revises: c967c71ad744
Create Date: 2021-07-26 20:29:40.445079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd50d9a94e77'
down_revision = 'c967c71ad744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentary',
                    sa.Column('column_not_exist_in_db',
                              sa.Integer(), nullable=False),
                    sa.Column('id_1', sa.Integer(), nullable=True),
                    sa.Column('text', sa.String(length=280), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('column_not_exist_in_db')
                    )
    op.create_table('rating',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_user', sa.Integer(), nullable=True),
                    sa.Column('id_project', sa.Integer(), nullable=True),
                    sa.Column('rating', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_column('projects', 'totalRatings')
    op.drop_column('projects', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column(
        'rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('totalRatings',
                  sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('rating')
    op.drop_table('commentary')
    # ### end Alembic commands ###
